name: 'Autometrics Diff Metrics'
description: 'Check the difference in autometrics coverage between the source and the target of a Pull Request.'
author: 'autometrics-dev'
branding:
  icon: 'bar-chart'
  color: 'purple'
inputs:
  gh-token:
    description: 'Github token to use'
    required: true
  rust-roots:
    description: 'The list of rust project roots to check. One path per line'
    required: false
  ts-roots:
    description: 'The list of typescript project roots to check. One path per line'
    required: false
  retention-days:
    description: 'The number of days to keep the artifacts for. Defaults to 0 (inherits the policy from the repository)'
    required: false
    default: 0
runs:
  using: 'node16'
  main: 'dist/index.js'
